name: Versioning

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 25

      - name: Install dependencies
        run: npm ci

      - name: Apply Changesets version
        run: npx changeset version

      - name: Commit version bump & changelog
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "chore: bump version and update changelog [skip ci]" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
